/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.srm.swings.billinfo;

import com.srm.services.dto.ServiceConstant;
import com.srm.services.entity.BillEntry;
import com.srm.services.entity.CategoryStock;
import com.srm.services.entity.CustomerDetails;
import com.srm.services.entity.HeaderSettings;
import com.srm.services.rest.services.TransactionService;
import com.srm.swings.util.AutoComplete;
import java.awt.Font;
import java.awt.Point;
import java.awt.event.ItemEvent;
import java.io.IOException;
import java.io.InputStream;
import java.util.HashMap;
import java.util.Map;
import javax.annotation.PostConstruct;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPopupMenu;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.plaf.FontUIResource;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import net.sf.jasperreports.engine.JREmptyDataSource;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanArrayDataSource;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.view.JasperViewer;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.springframework.util.StringUtils;

/**
 *
 * @author umprasad
 */
@Component
public class BillGenerateForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form billGenerateForm
     */
    @PostConstruct
    public void Init() throws IOException {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtFieldBillNo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtFieldCustName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtFieldCustContact = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtFieldPrice = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtFieldQty = new javax.swing.JTextField();
        btnAddItem = new javax.swing.JButton();
        btnRemoveItem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtableBillEntry = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        txtFieldTotalBill = new javax.swing.JTextField();
        btnRefresh = new javax.swing.JButton();
        txtFieldEntryDate = new com.toedter.calendar.JDateChooser();
        btnPrintBill = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jboxItemCode = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        txtFieldItemName = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtFieldQuantity = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtFieldDiscount = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtFieldTotalBillDis = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtFieldTotalAmt = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Sales Bill Generate");
        setFont(new java.awt.Font("Elephant", 0, 24)); // NOI18N

        jPanel1.setBackground(java.awt.SystemColor.window);
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 970, Short.MAX_VALUE)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Sales Bill Entry", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Elephant", 2, 24), new java.awt.Color(0, 51, 51))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setText("Bill Number");

        txtFieldBillNo.setEditable(false);
        txtFieldBillNo.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        txtFieldBillNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFieldBillNoKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setText("Bill Date");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setText("Customer Name");

        txtFieldCustName.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel7.setText("Mobile No.,");

        txtFieldCustContact.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        jButton10.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/save.png"))); // NOI18N
        jButton10.setText("Save");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton12.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edit_clear.png"))); // NOI18N
        jButton12.setText("Clean");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel11.setText("Price");

        txtFieldPrice.setEditable(false);
        txtFieldPrice.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        txtFieldPrice.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtFieldPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldPriceActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel9.setText("Qty");

        txtFieldQty.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        txtFieldQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldQtyActionPerformed(evt);
            }
        });

        btnAddItem.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        btnAddItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        btnAddItem.setEnabled(false);
        btnAddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddItemActionPerformed(evt);
            }
        });

        btnRemoveItem.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        btnRemoveItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/erase.png"))); // NOI18N
        btnRemoveItem.setEnabled(false);
        btnRemoveItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveItemActionPerformed(evt);
            }
        });

        jtableBillEntry.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jtableBillEntry.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sr No.", "Item Id", "Item Code", "Item Name", "Price", "Qty", "Discount(%)", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtableBillEntry.setRowHeight(45);
        setTableSettings(jtableBillEntry);
        jScrollPane1.setViewportView(jtableBillEntry);
        if (jtableBillEntry.getColumnModel().getColumnCount() > 0) {
            jtableBillEntry.getColumnModel().getColumn(0).setResizable(false);
        }
        creatCustomerBillWin();

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Amount");

        txtFieldTotalBill.setEditable(false);
        txtFieldTotalBill.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        txtFieldTotalBill.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtFieldTotalBill.setText("0");
        txtFieldTotalBill.setToolTipText("");

        btnRefresh.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cnr_update.png"))); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        txtFieldEntryDate.setDateFormatString("dd/MMM/yyy");
        txtFieldEntryDate.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        btnPrintBill.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnPrintBill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/printer.png"))); // NOI18N
        btnPrintBill.setText("Print");
        btnPrintBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintBillActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ITEM SEARCH", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Elephant", 0, 18))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel12.setText("Item Code");

        loadProdCodes();
        autoComplete=new AutoComplete(jboxItemCode);
        jboxItemCode.setEditable(true);
        jboxItemCode.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jboxItemCode.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jboxItemCodeItemStateChanged(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel10.setText("Item Name");

        txtFieldItemName.setEditable(false);
        txtFieldItemName.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel13.setText("Qunatity ");

        txtFieldQuantity.setEditable(false);
        txtFieldQuantity.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFieldQuantity))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jboxItemCode, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFieldItemName, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jboxItemCode, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(39, 39, 39)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtFieldItemName, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtFieldQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(109, Short.MAX_VALUE))
        );

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel14.setText("Discount");

        txtFieldDiscount.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        txtFieldDiscount.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtFieldDiscount.setText("0");
        txtFieldDiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldDiscountActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("Discount");

        txtFieldTotalBillDis.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        txtFieldTotalBillDis.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtFieldTotalBillDis.setText("0");
        txtFieldTotalBillDis.setToolTipText("");
        txtFieldTotalBillDis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldTotalBillDisActionPerformed(evt);
            }
        });
        txtFieldTotalBillDis.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFieldTotalBillDisKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFieldTotalBillDisKeyTyped(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("Total Bill");

        txtFieldTotalAmt.setEditable(false);
        txtFieldTotalAmt.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        txtFieldTotalAmt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtFieldTotalAmt.setText("0");
        txtFieldTotalAmt.setToolTipText("");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFieldPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFieldQty, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFieldDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(txtFieldBillNo, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(69, 69, 69)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtFieldEntryDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(txtFieldCustName, javax.swing.GroupLayout.PREFERRED_SIZE, 1146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(btnAddItem)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnRemoveItem))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(txtFieldCustContact, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnPrintBill, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(35, 35, 35)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFieldTotalBill, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtFieldTotalBillDis, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtFieldTotalAmt))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1603, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel6)
                        .addComponent(txtFieldBillNo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtFieldEntryDate, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFieldCustName, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFieldCustContact, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPrintBill, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel11)
                                .addComponent(txtFieldPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9)
                                .addComponent(txtFieldQty, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel14)
                                .addComponent(txtFieldDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnAddItem, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRemoveItem, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtFieldTotalAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtFieldTotalBillDis, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtFieldTotalBill, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)))
                .addGap(273, 273, 273))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFieldBillNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFieldBillNoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldBillNoKeyTyped

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        if(customerDetails==null){
            customerDetails=new CustomerDetails();
        }
        if (!StringUtils.isEmpty(txtFieldBillNo.getText())) {
            customerDetails.setBillNo(Long.parseLong(txtFieldBillNo.getText()));
        }
        customerDetails.setBillDate(txtFieldEntryDate.getDate());
        customerDetails.setCustomerName(txtFieldCustName.getText());
        customerDetails.setCustomerContact(txtFieldCustContact.getText());
        customerDetails.setAmount(Double.parseDouble(txtFieldTotalBill.getText()));
        customerDetails.setDiscount(Integer.valueOf(txtFieldTotalBillDis.getText()));
        customerDetails.setTotalAmount(Double.valueOf(txtFieldTotalAmt.getText()));
        if (customerDetails.getBillNo() != null) {
            if (transactionService.updateCustomerDetails(customerDetails)) {
                dialogBox(ServiceConstant.ACTION_UPDATE);
            }
        } else {
            customerDetails = transactionService.saveCutomerDetails(customerDetails);
            txtFieldBillNo.setText(customerDetails.getBillNo().toString());
            btnAddItem.setEnabled(Boolean.TRUE);
            btnRemoveItem.setEnabled(Boolean.TRUE);
            addCustomerRow(customerDetails);
            dialogBox(ServiceConstant.ACTION_SAVE);
        }

    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        clearFields(jPanel3);
        /*Customer Details object setting null*/
        customerDetails = null;
        /*Clear Datatable data*/
        clearTable(jtableBillEntry);
        txtFieldTotalBill.setText("0");
        txtFieldDiscount.setText("0");
        txtFieldTotalBillDis.setText("0");
        txtFieldTotalBill.setText("0");
        btnAddItem.setEnabled(Boolean.FALSE);
        btnRemoveItem.setEnabled(Boolean.FALSE);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void txtFieldPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldPriceActionPerformed

    private void txtFieldQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldQtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldQtyActionPerformed

    private void jboxItemCodeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jboxItemCodeItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED && jboxItemCode.getSelectedIndex() != 0) {
            CategoryStock categoryStock = transactionService.findProdNameAndPriceByProdCode(jboxItemCode.getSelectedItem().toString());
            if (categoryStock != null) {
                txtFieldItemName.setText(categoryStock.getProductName());
                txtFieldPrice.setText(categoryStock.getPrice().toString());
                txtFieldQuantity.setText(categoryStock.getQuantity().toString());
                txtFieldQty.setText("");
            } else {
                txtFieldItemName.setText("");
                txtFieldPrice.setText("");
                txtFieldQuantity.setText("");
                txtFieldQty.setText("");
            }
        } else {
            txtFieldItemName.setText("");
            txtFieldPrice.setText("");
            txtFieldQuantity.setText("");
            txtFieldQty.setText("");
        }
    }//GEN-LAST:event_jboxItemCodeItemStateChanged

    private void btnAddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddItemActionPerformed
        BillEntry billEntry = new BillEntry();
        billEntry.setProdCode(jboxItemCode.getSelectedItem().toString());
        billEntry.setProdName(txtFieldItemName.getText());
        billEntry.setPrice(Double.parseDouble(txtFieldPrice.getText()));
        billEntry.setQty(Integer.parseInt(txtFieldQty.getText()));
        billEntry.setDiscount(Integer.parseInt(txtFieldDiscount.getText()));
        Double totalAmt = billEntry.getPrice() * billEntry.getQty();
        if(billEntry.getDiscount()!=0){
            totalAmt=ServiceConstant.calcDiscount(totalAmt,billEntry.getDiscount());
        }
        billEntry.setAmount(totalAmt);
        Double totalBillAmt = Double.valueOf(txtFieldTotalBill.getText());
        totalBillAmt += billEntry.getAmount();
        txtFieldTotalBill.setText(totalBillAmt.toString());
        txtFieldTotalAmt.setText(totalBillAmt.toString());
        customerDetails.setAmount(totalBillAmt);
        customerDetails.setTotalAmount(totalBillAmt);
        billEntry.setCustomerDetails(customerDetails);
        billEntry = transactionService.saveBillDetails(billEntry);
        addRow(billEntry);
        jboxItemCode.setSelectedIndex(0);
        txtFieldItemName.setText("");
        txtFieldPrice.setText("");
        txtFieldQuantity.setText("");
        txtFieldQty.setText("");
        txtFieldDiscount.setText("0");
    }//GEN-LAST:event_btnAddItemActionPerformed

    private void btnRemoveItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveItemActionPerformed
        Integer rowIndex = jtableBillEntry.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) jtableBillEntry.getModel();
        Long billId = (Long) model.getValueAt(rowIndex, 1);
        Double amount = (Double) model.getValueAt(rowIndex,7);
        Double totalAmt = Double.parseDouble(txtFieldTotalBill.getText());
        totalAmt -= amount;
        Integer discount=Integer.valueOf(txtFieldTotalBillDis.getText());
        txtFieldTotalBill.setText(totalAmt.toString());
        totalAmt=ServiceConstant.calcDiscount(totalAmt,discount);
        txtFieldTotalAmt.setText(totalAmt.toString());
        if (transactionService.deleteBillDetails(billId)) {
            model.removeRow(rowIndex);
            jboxItemCode.setSelectedIndex(0);
            txtFieldItemName.setText("");
            txtFieldPrice.setText("");
            txtFieldQuantity.setText("");
            txtFieldQty.setText("");
        }
    }//GEN-LAST:event_btnRemoveItemActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        loadProdCodes();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnPrintBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintBillActionPerformed
        HeaderSettings headerSettings = transactionService.findHeaderSettingByUse(ServiceConstant.DEFAULT_USE_YES);
//        BillReceiptView billReceiptView = new BillReceiptView(customerDetails, headerSettings);
//        billReceiptView.printReceipt();
//        PrintView printView = new PrintView(null, true);
//        printView.setLocationRelativeTo(this);
//        printView.setBillReceiptView(billReceiptView);
//        printView.show();
        try{
            Map<String,Object> params=new HashMap<String, Object>();
            params.put("companyName",headerSettings.getCompanyName());
            params.put("address",headerSettings.getAddress());
            params.put("addressSub",headerSettings.getAddressSub());
            params.put("gstNo",headerSettings.getRegistrationNo());
            //params.put("billNo",customerDetails.getBillNo());
            params.put("billDate",customerDetails.getBillDate());
            params.put("customerName",customerDetails.getCustomerName());
             params.put("customerDetails",customerDetails);
            InputStream inputStream=this.getClass().getResourceAsStream("/reports/invoice.jrxml");
            JasperReport report=JasperCompileManager.compileReport(inputStream);
            fillReport=JasperFillManager.fillReport(report,params,new JRBeanArrayDataSource(new CustomerDetails[]{customerDetails}));
            JasperViewer.viewReport(fillReport,false);
        }catch(Exception ex){
            LOGGER.error("Exception{}"+ex.getMessage(),ex);
        }
    }//GEN-LAST:event_btnPrintBillActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       if(jPopupMenu==null){
           jPopupMenu=new JPopupMenu();
           jPopupMenu.add(popupPanel);
       }
       Point point=txtFieldCustName.getLocationOnScreen();
       jPopupMenu.show(this,0,0);
       jPopupMenu.setLocation(point.x,point.y+txtFieldCustName.getHeight());
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtFieldDiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldDiscountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldDiscountActionPerformed

    private void txtFieldTotalBillDisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldTotalBillDisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldTotalBillDisActionPerformed

    private void txtFieldTotalBillDisKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFieldTotalBillDisKeyReleased
         Double totalAmt=0d;
        Integer discount=0;
        if(Character.isDigit(evt.getKeyCode())){
            discount=Integer.parseInt(txtFieldTotalBillDis.getText());
            totalAmt=customerDetails.getAmount();
            if(discount.intValue()!=0){
                totalAmt=ServiceConstant.calcDiscount(totalAmt, discount);
            }
            customerDetails.setDiscount(discount);
            customerDetails.setTotalAmount(totalAmt);
            txtFieldTotalAmt.setText(totalAmt.toString());
        }
    }//GEN-LAST:event_txtFieldTotalBillDisKeyReleased

    private void txtFieldTotalBillDisKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFieldTotalBillDisKeyTyped
      
    }//GEN-LAST:event_txtFieldTotalBillDisKeyTyped

    private void setTableSettings(JTable jTable) {
        Font font = new FontUIResource("Times New Roman", Font.PLAIN, 28);
        JTableHeader header = jTable.getTableHeader();
        header.setFont(font);
    }

    private void loadProdCodes() {
        java.util.List<String> prodCodes = transactionService.findAllProuctCodes();
        prodCodes.add(0, ServiceConstant.SELECTED);
        jboxItemCode.setModel(new DefaultComboBoxModel(prodCodes.toArray()));

    }

    private void loadCustomerDetails() {
        java.util.List<CustomerDetails> customerDetailses = transactionService.findAllCustomerDetails();
        if (customerDetailses != null) {
            for (CustomerDetails customerDetail : customerDetailses) {
                addCustomerRow(customerDetail);
            }
        }
        customerDetailses.clear();
        customerDetailses = null;
    }

    private void clearFields(java.awt.Component component) {
        if (component instanceof JPanel) {
            for (java.awt.Component comp : ((JPanel) component).getComponents()) {
                if (comp instanceof JTextField) {
                    ((JTextField) comp).setText("");
                } else if (comp instanceof JComboBox) {
                    ((JComboBox) comp).setSelectedIndex(0);
                }
            }
        }
    }

    private void clearTable(JTable jTable) {
        DefaultTableModel model = (DefaultTableModel) jTable.getModel();
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
    }

    private void addRow(BillEntry billEntry) {
        DefaultTableModel model = (DefaultTableModel) jtableBillEntry.getModel();
        model.addRow(new Object[]{
            model.getRowCount() + 1,
            billEntry.getBillId(), billEntry.getProdCode(), billEntry.getProdName(),
            billEntry.getPrice(), billEntry.getQty(),billEntry.getDiscount(),billEntry.getAmount()
        });
    }

    private void addCustomerRow(CustomerDetails customerDetail) {
        DefaultTableModel model = (DefaultTableModel) jtableCustomerDetails.getModel();
        model.addRow(new Object[]{customerDetail.getBillNo(), customerDetail.getCustomerName()});
    }

    private void dialogBox(Integer action) {
        if (ServiceConstant.ACTION_SAVE.equals(action)) {
            JOptionPane.showMessageDialog(this, ServiceConstant.SUCCESS_MSG, ServiceConstant.RESULT_SUCCESS,
                    JOptionPane.INFORMATION_MESSAGE);
        } else if (ServiceConstant.ACTION_UPDATE.equals(action)) {
            JOptionPane.showMessageDialog(this, ServiceConstant.UPDATE_MSG, ServiceConstant.RESULT_SUCCESS,
                    JOptionPane.INFORMATION_MESSAGE);
        } else if (ServiceConstant.ACTION_DELETE.equals(action)) {
            JOptionPane.showMessageDialog(this, ServiceConstant.DETLE_MSG, ServiceConstant.RESULT_SUCCESS,
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }

    private void creatCustomerBillWin() {
        popupPanel = new javax.swing.JPanel();
        popupPanel.setBackground(new java.awt.Color(59, 81, 73));
        popupPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Customer Bill Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Elephant", 0, 24), java.awt.Color.yellow)); // NOI18N
        JScrollPane jScrollPane = new JScrollPane();
        popupPanel.add(jScrollPane);
        jtableCustomerDetails = new javax.swing.JTable();
        jtableCustomerDetails.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jtableCustomerDetails.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Bill No", "Customer Name"
                }
        ) {
            Class[] types = new Class[]{
                java.lang.Long.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean[]{
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });

        jtableCustomerDetails.setRowHeight(45);
        setTableSettings(jtableCustomerDetails);
        jtableCustomerDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtableCustomerDetailsMousePressed(evt);
            }
        });
        jScrollPane.setSize(popupPanel.getWidth(),popupPanel.getHeight()-4);
        jScrollPane.setViewportView(jtableCustomerDetails);
        loadCustomerDetails();
    }
    private void jtableCustomerDetailsMousePressed(java.awt.event.MouseEvent evt) {                                                   
        DefaultTableModel model=(DefaultTableModel)jtableCustomerDetails.getModel();
        Integer rowIndex=jtableCustomerDetails.getSelectedRow();
        if(rowIndex!=-1){
            Long billNo=(Long)model.getValueAt(rowIndex,0);
            customerDetails=transactionService.findCustomerByBillId(billNo);
            if(customerDetails!=null){
                txtFieldBillNo.setText(customerDetails.getBillNo().toString());
                txtFieldEntryDate.setDate(customerDetails.getBillDate());
                txtFieldCustName.setText(customerDetails.getCustomerName());
                txtFieldCustContact.setText(customerDetails.getCustomerContact());
                btnAddItem.setEnabled(Boolean.TRUE);
                btnRemoveItem.setEnabled(Boolean.TRUE);
                txtFieldTotalBill.setText("0");
                Double totalBillAmt=Double.valueOf(txtFieldTotalBill.getText());
                clearTable(jtableBillEntry);
                if(customerDetails.getBillEntrys()!=null){
                    for(BillEntry billEntry:customerDetails.getBillEntrys()){
                        totalBillAmt+=billEntry.getAmount();
                        addRow(billEntry);
                    }
                }
                txtFieldTotalBill.setText(totalBillAmt.toString());
                if(customerDetails.getDiscount()!=null){
                    txtFieldTotalBillDis.setText(customerDetails.getDiscount().toString());
                }
                if(customerDetails.getTotalAmount()!=null){
                    txtFieldTotalAmt.setText(customerDetails.getTotalAmount().toString());
                }else{
                    txtFieldTotalAmt.setText(totalBillAmt.toString());
                }
            }
        }
    }         
    private CustomerDetails customerDetails = null;
    @Autowired
    private TransactionService transactionService;
    private JPopupMenu jPopupMenu = null;
    private JPanel popupPanel = null;
    private JTable jtableCustomerDetails = null;
    private  JasperPrint fillReport=null;
    private AutoComplete autoComplete=null;
    private static final Logger LOGGER=LoggerFactory.getLogger(BillGenerateForm.class);
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddItem;
    private javax.swing.JButton btnPrintBill;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnRemoveItem;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton12;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox jboxItemCode;
    private javax.swing.JTable jtableBillEntry;
    private javax.swing.JTextField txtFieldBillNo;
    private javax.swing.JTextField txtFieldCustContact;
    private javax.swing.JTextField txtFieldCustName;
    private javax.swing.JTextField txtFieldDiscount;
    private com.toedter.calendar.JDateChooser txtFieldEntryDate;
    private javax.swing.JTextField txtFieldItemName;
    private javax.swing.JTextField txtFieldPrice;
    private javax.swing.JTextField txtFieldQty;
    private javax.swing.JTextField txtFieldQuantity;
    private javax.swing.JTextField txtFieldTotalAmt;
    private javax.swing.JTextField txtFieldTotalBill;
    private javax.swing.JTextField txtFieldTotalBillDis;
    // End of variables declaration//GEN-END:variables
}
