/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.srm.swings.settings;

import com.srm.services.dto.ServiceConstant;
import com.srm.services.entity.UserInfo;
import com.srm.services.rest.services.TransactionService;
import com.srm.swings.encription.SecureEncryption;
import com.srm.swings.util.UIUtils;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.annotation.PostConstruct;
import javax.swing.JTree;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreeNode;
import javax.swing.tree.TreePath;
import org.dom4j.swing.LeafTreeNode;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.springframework.util.StringUtils;

/**
 *
 * @author umprasad
 */
@Component
public class NewUserForm extends javax.swing.JDialog {

    /**
     * Creates new form NewUserForm
     */
    @PostConstruct
    public void init() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        userdetailsPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textFieldUserId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textFieldUserName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textFieldLoginId = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        textFieldPassword = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jRadioYes = new javax.swing.JRadioButton();
        jRadioNo = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        permissionPanel = new javax.swing.JPanel();
        jCheckBillEntry = new javax.swing.JCheckBox();
        jCheckStockentry = new javax.swing.JCheckBox();
        jChecknewUser = new javax.swing.JCheckBox();
        jCheckViewReports = new javax.swing.JCheckBox();
        jCheckSystems = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTreeUsersList = new javax.swing.JTree();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        userdetailsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "New User", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Elephant", 0, 24))); // NOI18N

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/list_add_user.png"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        jLabel2.setText("User ID");

        textFieldUserId.setEditable(false);
        textFieldUserId.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        jLabel3.setText("User Name");

        textFieldUserName.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        jLabel4.setText("Login ID");

        textFieldLoginId.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        jLabel5.setText("Password");

        textFieldPassword.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        jLabel6.setText("Active");

        buttonGroup1.add(jRadioYes);
        jRadioYes.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        jRadioYes.setText("Yes");
        jRadioYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioYesActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioNo);
        jRadioNo.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        jRadioNo.setSelected(true);
        jRadioNo.setText("No");
        jRadioNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioNoActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 51, 0));
        jLabel7.setText("*");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 51, 0));
        jLabel8.setText("*");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 51, 0));
        jLabel9.setText("*");

        permissionPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Permissions", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 24))); // NOI18N

        jCheckBillEntry.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jCheckBillEntry.setText("Bill Entry");

        jCheckStockentry.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jCheckStockentry.setText("Stock Entry");

        jChecknewUser.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jChecknewUser.setText("New User");

        jCheckViewReports.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jCheckViewReports.setText("View Reports");

        jCheckSystems.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jCheckSystems.setText("System Settings");

        javax.swing.GroupLayout permissionPanelLayout = new javax.swing.GroupLayout(permissionPanel);
        permissionPanel.setLayout(permissionPanelLayout);
        permissionPanelLayout.setHorizontalGroup(
            permissionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(permissionPanelLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jCheckBillEntry)
                .addGap(40, 40, 40)
                .addComponent(jCheckStockentry)
                .addGap(43, 43, 43)
                .addComponent(jChecknewUser)
                .addGap(42, 42, 42)
                .addComponent(jCheckViewReports)
                .addGap(33, 33, 33)
                .addComponent(jCheckSystems)
                .addContainerGap(92, Short.MAX_VALUE))
        );
        permissionPanelLayout.setVerticalGroup(
            permissionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(permissionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(permissionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBillEntry)
                    .addComponent(jCheckStockentry)
                    .addComponent(jChecknewUser)
                    .addComponent(jCheckViewReports)
                    .addComponent(jCheckSystems))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout userdetailsPanelLayout = new javax.swing.GroupLayout(userdetailsPanel);
        userdetailsPanel.setLayout(userdetailsPanelLayout);
        userdetailsPanelLayout.setHorizontalGroup(
            userdetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userdetailsPanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(userdetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(userdetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userdetailsPanelLayout.createSequentialGroup()
                        .addGroup(userdetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(userdetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(userdetailsPanelLayout.createSequentialGroup()
                                .addGroup(userdetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(userdetailsPanelLayout.createSequentialGroup()
                                        .addComponent(jRadioYes)
                                        .addGap(59, 59, 59)
                                        .addComponent(jRadioNo)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(userdetailsPanelLayout.createSequentialGroup()
                                        .addComponent(textFieldUserId, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())
                            .addGroup(userdetailsPanelLayout.createSequentialGroup()
                                .addGroup(userdetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textFieldLoginId, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textFieldUserName))
                                .addGap(311, 311, 311))))
                    .addGroup(userdetailsPanelLayout.createSequentialGroup()
                        .addComponent(permissionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 102, Short.MAX_VALUE))))
        );
        userdetailsPanelLayout.setVerticalGroup(
            userdetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userdetailsPanelLayout.createSequentialGroup()
                .addGroup(userdetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(userdetailsPanelLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(userdetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(textFieldUserId, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(userdetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(textFieldUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGroup(userdetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(userdetailsPanelLayout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addGroup(userdetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel7))
                                .addGap(61, 61, 61))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userdetailsPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldLoginId, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)))
                        .addGroup(userdetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(textFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(46, 46, 46)
                        .addGroup(userdetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jRadioYes)
                            .addComponent(jRadioNo))))
                .addGap(40, 40, 40)
                .addComponent(permissionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jTreeUsersList.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jTreeUsersList.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jTreeUsersList.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                jTreeUsersListValueChanged(evt);
            }
        });
        jTreeUsersList.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                jTreeUsersListVetoableChange(evt);
            }
        });
        jScrollPane1.setViewportView(jTreeUsersList);
        loadUsers();

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/erase.png"))); // NOI18N
        jButton2.setText("Remove");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edit_clear.png"))); // NOI18N
        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/save.png"))); // NOI18N
        jButton4.setText("Save");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(userdetailsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(57, 57, 57))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(userdetailsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioYesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioYesActionPerformed

    private void jRadioNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioNoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       UIUtils.clearFields(userdetailsPanel);
       UIUtils.clearFields(permissionPanel);
       jRadioNo.setSelected(true);
       textFieldPassword.setEditable(true);
       textFieldLoginId.setEditable(true);
       userInfo=null;
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       userInfo=new  UserInfo();
       if(!StringUtils.isEmpty(textFieldUserId.getText())){
           userInfo.setId(Long.valueOf(textFieldUserId.getText()));
       }
       userInfo.setUserName(textFieldUserName.getText());
       userInfo.setLoginId(textFieldLoginId.getText());
       userInfo.setBillEntryAccess(jCheckBillEntry.isSelected());
       userInfo.setStockEntryAccess(jCheckStockentry.isSelected());
       userInfo.setNewuserAccess(jChecknewUser.isSelected());
       userInfo.setViewReportAccess(jCheckViewReports.isSelected());
       userInfo.setSystemAccess(jCheckSystems.isSelected());
       userInfo.setActive(jRadioYes.isSelected()?ServiceConstant.DEFAULT_USE_YES:ServiceConstant.DEFAULT_USE_NO);
        try{
            userInfo.setPassWord(secureEncryption.encrypt(textFieldPassword.getText()));
        }catch (Exception ex) {
            Logger.getLogger(NewUserForm.class.getName()).log(Level.SEVERE, null, ex);
        }
       if(userInfo.getId()==null){
           userInfo=transactionService.saveUserDetails(userInfo);
           textFieldUserId.setText(userInfo.getId().toString());
           UIUtils.dialogBox(ServiceConstant.ACTION_SAVE,this);
           updateUsers(userInfo);
       }else if(transactionService.updateUserDetails(userInfo)){
           UIUtils.dialogBox(ServiceConstant.ACTION_UPDATE,this);
       }
       
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTreeUsersListValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_jTreeUsersListValueChanged
        TreePath treePath=evt.getNewLeadSelectionPath();
        DefaultMutableTreeNode selectedUser=(DefaultMutableTreeNode)treePath.getLastPathComponent();
        if(selectedUser.getUserObject()!=null){
            userInfo=transactionService.findUserByLoginId(selectedUser.getUserObject().toString());
            if(userInfo!=null){
                textFieldPassword.setEditable(false);
                textFieldLoginId.setEditable(false);
                textFieldUserId.setText(userInfo.getId().toString());
                textFieldUserName.setText(userInfo.getUserName());
                textFieldLoginId.setText(userInfo.getLoginId());
                try {
                    textFieldPassword.setText(secureEncryption.decrypt(userInfo.getPassWord()));
                } catch (Exception ex) {
                    Logger.getLogger(NewUserForm.class.getName()).log(Level.SEVERE, null, ex);
                }
                if(userInfo.getActive()!=null && ServiceConstant.DEFAULT_USE_YES.equals(userInfo.getActive())){
                    jRadioYes.setSelected(true);
                }else{
                    jRadioNo.setSelected(true);
                }
                jCheckBillEntry.setSelected(userInfo.isBillEntryAccess());
                jCheckStockentry.setSelected(userInfo.isStockEntryAccess());
                jChecknewUser.setSelected(userInfo.isNewuserAccess());
                jCheckViewReports.setSelected(userInfo.isViewReportAccess());
                jCheckSystems.setSelected(userInfo.isSystemAccess());
            }
        }
          
    }//GEN-LAST:event_jTreeUsersListValueChanged

    private void jTreeUsersListVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_jTreeUsersListVetoableChange
       
    }//GEN-LAST:event_jTreeUsersListVetoableChange
    private void updateUsers(UserInfo userInfo){
        rootNode.add(new DefaultMutableTreeNode(userInfo.getLoginId()));
        userTreeModel.reload();
    }
    private void loadUsers(){
        rootNode=new  DefaultMutableTreeNode("USERS");
        userTreeModel=new DefaultTreeModel(rootNode);
        jTreeUsersList.setModel(userTreeModel);
        List<UserInfo> userInfos=transactionService.findAllUserDetails();
        for(UserInfo userInfo:userInfos){
            rootNode.add(new DefaultMutableTreeNode(userInfo.getLoginId()));
        }
    }
    private DefaultTreeModel userTreeModel;
    private DefaultMutableTreeNode rootNode;
    private UserInfo userInfo=null;
    @Autowired private TransactionService transactionService;
    @Autowired private SecureEncryption secureEncryption;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBillEntry;
    private javax.swing.JCheckBox jCheckStockentry;
    private javax.swing.JCheckBox jCheckSystems;
    private javax.swing.JCheckBox jCheckViewReports;
    private javax.swing.JCheckBox jChecknewUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioNo;
    private javax.swing.JRadioButton jRadioYes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jTreeUsersList;
    private javax.swing.JPanel permissionPanel;
    private javax.swing.JTextField textFieldLoginId;
    private javax.swing.JPasswordField textFieldPassword;
    private javax.swing.JTextField textFieldUserId;
    private javax.swing.JTextField textFieldUserName;
    private javax.swing.JPanel userdetailsPanel;
    // End of variables declaration//GEN-END:variables
}
