/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NextWindow.java
 *
 * Created on Jul 4, 2017, 11:10:39 PM
 */

package com.srm.swings.components;

import com.srm.services.dto.SessionDetails;
import com.srm.services.entity.UserInfo;
import com.srm.swings.billinfo.BillGenerateForm;
import com.srm.swings.luncher.LoginForm;
import com.srm.swings.product.ProductCategory;
import com.srm.swings.settings.HeaderSetting;
import com.srm.swings.settings.NewUserForm;
import javax.annotation.PostConstruct;
import javax.swing.SwingUtilities;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
 *
 * @author umprasad
 */
@Component
public class NextWindow extends javax.swing.JFrame {

    private static final Logger LOGGER=LoggerFactory.getLogger(NextWindow.class);
    /** Creates new form NextWindow */
    @PostConstruct
    public void init() {
        setUndecorated(false);
        initComponents();
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelloginUser = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        productCategoryMenu = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        salesBillEntryMenu = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        headerSettingMenuitem = new javax.swing.JMenuItem();
        newuserMenuitem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SRCOMMUNICATIONS");
        setFont(new java.awt.Font("Elephant", 0, 36)); // NOI18N

        jDesktopPane=new MDIDesktopPane();
        jScrollPane1.setViewportView(jDesktopPane);

        jPanel2.setBackground(new java.awt.Color(223, 190, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Elephant", 3, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user.png"))); // NOI18N
        jLabel1.setText("Welcome");

        labelloginUser.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        labelloginUser.setText("login");

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exit.png"))); // NOI18N
        jButton1.setText("SignOut");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelloginUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(labelloginUser))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jButton1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(0, 43, 27));
        jMenuBar1.setForeground(new java.awt.Color(153, 153, 0));

        jMenu1.setForeground(new java.awt.Color(102, 102, 0));
        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/productadd.png"))); // NOI18N
        jMenu1.setText("Product Master");
        jMenu1.setBorderPainted(true);
        jMenu1.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N

        productCategoryMenu.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        productCategoryMenu.setText("Product Categories");
        productCategoryMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productCategoryMenuActionPerformed(evt);
            }
        });
        jMenu1.add(productCategoryMenu);

        jMenuBar1.add(jMenu1);

        jMenu2.setForeground(new java.awt.Color(102, 102, 0));
        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billing.png"))); // NOI18N
        jMenu2.setText("Bill Generate");
        jMenu2.setBorderPainted(true);
        jMenu2.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N

        salesBillEntryMenu.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        salesBillEntryMenu.setText("Sales Bill Entry");
        salesBillEntryMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salesBillEntryMenuActionPerformed(evt);
            }
        });
        jMenu2.add(salesBillEntryMenu);

        jMenuBar1.add(jMenu2);

        jMenu3.setForeground(new java.awt.Color(102, 102, 0));
        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/settings.png"))); // NOI18N
        jMenu3.setText("Settings");
        jMenu3.setBorderPainted(true);
        jMenu3.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N

        headerSettingMenuitem.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        headerSettingMenuitem.setText("Header Setting");
        headerSettingMenuitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                headerSettingMenuitemActionPerformed(evt);
            }
        });
        jMenu3.add(headerSettingMenuitem);

        newuserMenuitem.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        newuserMenuitem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user.png"))); // NOI18N
        newuserMenuitem.setText("New User");
        newuserMenuitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newuserMenuitemActionPerformed(evt);
            }
        });
        jMenu3.add(newuserMenuitem);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);
        jMenuBar1.getAccessibleContext().setAccessibleParent(this);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1709, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 904, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void productCategoryMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productCategoryMenuActionPerformed
        // TODO add your handling code here:
        //productCategory.init();
        productCategory.show();
        jDesktopPane.add(productCategory);
    }//GEN-LAST:event_productCategoryMenuActionPerformed

    private void salesBillEntryMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salesBillEntryMenuActionPerformed
        billGenerateForm.show();
        jDesktopPane.add(billGenerateForm);
    }//GEN-LAST:event_salesBillEntryMenuActionPerformed

    private void headerSettingMenuitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_headerSettingMenuitemActionPerformed
       headerSetting.setLocationRelativeTo(this);
       headerSetting.show();
    }//GEN-LAST:event_headerSettingMenuitemActionPerformed

    private void newuserMenuitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newuserMenuitemActionPerformed
        newUserForm.setLocationRelativeTo(this);
        newUserForm.show();
    }//GEN-LAST:event_newuserMenuitemActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        loginForm.setLocationRelativeTo(null);
        loginForm.show();
    }//GEN-LAST:event_jButton1ActionPerformed
    public void setLoginId(){
         labelloginUser.setText(userSession.getUserName());
         UserInfo userInfo=userSession.getUserInfo();
         if(userInfo.isStockEntryAccess()){
             productCategoryMenu.setEnabled(true);
         }else{
             productCategoryMenu.setEnabled(false);
         }
         if(userInfo.isBillEntryAccess()){
             salesBillEntryMenu.setEnabled(true);
         }else{
             salesBillEntryMenu.setEnabled(false);
         }
         if(userInfo.isNewuserAccess()){
             newuserMenuitem.setEnabled(true);
         }else{
             newuserMenuitem.setEnabled(false);
         }
         if(userInfo.isSystemAccess()){
            headerSettingMenuitem.setEnabled(true);
         }else{
            headerSettingMenuitem.setEnabled(false);
         }
    }
    @Autowired ProductCategory productCategory;
    @Autowired BillGenerateForm billGenerateForm;
    @Autowired HeaderSetting headerSetting;
    @Autowired SessionDetails userSession;
    @Autowired NewUserForm newUserForm;
    @Autowired LoginForm loginForm;
    private MDIDesktopPane jDesktopPane;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem headerSettingMenuitem;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelloginUser;
    private javax.swing.JMenuItem newuserMenuitem;
    private javax.swing.JMenuItem productCategoryMenu;
    private javax.swing.JMenuItem salesBillEntryMenu;
    // End of variables declaration//GEN-END:variables

}
